title: Christopher Le
description: Symmetry & Degeneracy in Quantum States
logo: 
show_downloads: true
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme 
markdown: kramdown
kramdown:
  math_engine: mathjax
